### ISSUE TITLE
PHP8.1 support: `ctype-digit` passing a non-string argument is deprecated

### ISSUE THREAD

**Issue by pjayme** [madmatt/silverstripe-encrypt-at-rest#24]
On PHP8.1, [ctype-digit()](https://www.php.net/manual/en/function.ctype-xdigit.php) passing a non-string argument is deprecated and is advised that the value should be cast to a `string` or an explicit call to [chr()](https://www.php.net/manual/en/function.chr.php) should be made.

The issue can be found in [this](https://github.com/madmatt/silverstripe-encrypt-at-rest/blob/master/code/fieldtypes/EncryptedText.php#L29) line of code.

**Comment by madmatt** [comment]
Fixed in #25.
